version: '3.9'
services:
  db:
    image: postgres:17
    container_name: mydigitalwallet_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MyDigitalWalletDb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: mydigitalwallet_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MyDigitalWalletDb;Username=postgres;Password=postgres
    depends_on:
      - db

volumes:
  dbdata:
